name: Auto-asignar revisor si hay 5 commits

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install PyGithub GitPython

      - name: Construir contexto 
        run: python .github/workflows/scripts/build_user_contexts.py

      - name: Run reviewer assignment script
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        run: python .github/workflows/scripts/assign_reviewer.py
